### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dragosgaftoneanu-okta**
Modified Login Redirect URI section as per report from support case 00570237.

### CODE REVIEW

**Comment by redbmk** [comment]
Thanks! I'll have to check and see if there are other repos with the same mistake.

**Comment by mraible** [comment]
@dragosgaftoneanu-okta Does the blog post need to be updated too? I'm not sure if there's a companion blog post since this repo doesn't link back to it.

**Comment by dragosgaftoneanu-okta** [comment]
Hi @mraible 

I did not find any blogs linked to this repository.

**Comment by mraible** [comment]
It appears to be a Scotch.io article: https://scotch.io/tutorials/build-simple-authentication-in-express-in-15-minutes

screen shot 2019-03-05 at 7 43 13 am

I'll try to get access and fix it. Note that there's a comment pointing out additional issues.

**Pull request merged**
